import { NativeModules, PermissionsAndroid } from 'react-native';
import { AI_MODEL_ASSETS } from '../modelAssets';
import { parseNluJson } from '../nlu/jsonParser';
import { buildNluPrompt } from '../nlu/prompt';
import { createFallbackNluResult, processCommand } from '../nlu/parser';
import { applyNluScheduleResult } from '../nlu/scheduler';
import type { CreatedScheduleItemType, NluResult } from '../nlu/types';
import type { OfflineModelReference } from '../modelAssets';
import {
  hasOfflineSpeechCapture,
  startOfflineSpeechCapture,
} from './speechCapture';
const LLM_MAX_TOKENS = 220;
const LLM_TEMPERATURE = 0;

interface IntentExtractionRequest {
  transcript: string;
  prompt: string;
  model: OfflineModelReference;
  temperature: number;
  maxTokens: number;
}

interface LafinaIntentExtractorModule {
  extractIntentJson: (request: IntentExtractionRequest) => Promise<string>;
}

interface OfflineVoiceNativeModules {
  LafinaIntentExtractor?: LafinaIntentExtractorModule;
}

export type VoicePipelineErrorCode =
  | 'permission_denied'
  | 'native_runtime_unavailable'
  | 'no_speech_detected'
  | 'empty_transcript'
  | 'processing_failed';

export interface VoicePipelineResult {
  didUpdate: boolean;
  transcript: string;
  reply: string;
  createdItemType: CreatedScheduleItemType | null;
  nluResult: NluResult | null;
  errorCode: VoicePipelineErrorCode | null;
}

const getNativeVoiceModules = (): OfflineVoiceNativeModules => {
  return NativeModules as unknown as OfflineVoiceNativeModules;
};

const requestMicrophonePermission = async (): Promise<boolean> => {
  try {
    const result = await PermissionsAndroid.request(
      PermissionsAndroid.PERMISSIONS.RECORD_AUDIO,
    );
    return result === PermissionsAndroid.RESULTS.GRANTED;
  } catch {
    return false;
  }
};

const unavailableResult = (
  reply: string,
  errorCode: VoicePipelineErrorCode,
): VoicePipelineResult => ({
  didUpdate: false,
  transcript: '',
  reply,
  createdItemType: null,
  nluResult: null,
  errorCode,
});

/**
 * Checks whether all offline Android voice runtime modules are registered.
 *
 * @returns True when recording, STT, and LLM native modules are available.
 */
export const hasOfflineVoiceRuntime = (): boolean => {
  const modules = getNativeVoiceModules();
  return hasOfflineSpeechCapture() && Boolean(modules.LafinaIntentExtractor);
};

/**
 * Records a spoken command, transcribes it locally, extracts NLU JSON locally, and applies it.
 *
 * @param userId Active local user ID that owns any created schedule item.
 * @returns The pipeline result, including transcript, reply, and storage update status.
 */
export const runOfflineVoiceScheduling = async (
  userId: string,
): Promise<VoicePipelineResult> => {
  const modules = getNativeVoiceModules();

  if (!hasOfflineSpeechCapture() || !modules.LafinaIntentExtractor) {
    return unavailableResult(
      'Offline voice is not available in this build yet. You can type the command below for now.',
      'native_runtime_unavailable',
    );
  }

  const hasPermission = await requestMicrophonePermission();
  if (!hasPermission) {
    return unavailableResult(
      'Microphone permission is needed before I can listen for a schedule command.',
      'permission_denied',
    );
  }

  try {
    const capture = startOfflineSpeechCapture({
      mode: 'automatic',
      bargeIn: false,
      context: 'main_mic',
    });
    const transcription = await capture.result;
    if (!transcription.speechDetected) {
      return unavailableResult(
        "I didn't hear speech clearly enough to schedule anything.",
        'no_speech_detected',
      );
    }
    const transcript = transcription.transcript.trim();
    if (transcript.length === 0) {
      return unavailableResult(
        "I couldn't transcribe that speech clearly enough to schedule it.",
        'empty_transcript',
      );
    }

    const rawNluJson = await modules.LafinaIntentExtractor.extractIntentJson({
      transcript,
      prompt: buildNluPrompt(transcript),
      model: AI_MODEL_ASSETS.llm,
      temperature: LLM_TEMPERATURE,
      maxTokens: LLM_MAX_TOKENS,
    });

    const nluResult = parseNluJson(rawNluJson);
    const scheduleResult = applyNluScheduleResult(nluResult, userId);

    return {
      didUpdate: scheduleResult.didUpdate,
      transcript,
      reply: scheduleResult.reply,
      createdItemType: scheduleResult.createdItemType,
      nluResult,
      errorCode: null,
    };
  } catch (error) {
    console.error('Offline voice scheduling failed:', error);
    return unavailableResult(
      'Sorry, I could not process that speech command locally.',
      'processing_failed',
    );
  }
};

/**
 * Processes text input using the local SmolLM2 LLM chatbot engine.
 *
 * @param userText Message typed or spoken by the user.
 * @param userId Active user ID.
 * @returns Conversational reply generated by the local SmolLM2 LLM.
 */
export const runLocalLlmChat = async (
  userText: string,
  userId: string,
): Promise<string> => {
  const modules = getNativeVoiceModules();
  const deterministicResult = createFallbackNluResult(userText);

  // Scheduling commands are handled deterministically first. This avoids an
  // unnecessary native-model round trip and keeps title/date extraction
  // consistent between typed chat and the offline fallback path.
  if (deterministicResult.intent === 'schedule') {
    return applyNluScheduleResult(deterministicResult, userId).reply;
  }

  if (modules.LafinaIntentExtractor) {
    try {
      const rawNluJson = await modules.LafinaIntentExtractor.extractIntentJson({
        transcript: userText,
        prompt: buildNluPrompt(userText),
        model: AI_MODEL_ASSETS.llm,
        temperature: LLM_TEMPERATURE,
        maxTokens: LLM_MAX_TOKENS,
      });

      const nluResult = parseNluJson(rawNluJson);
      const scheduleResult = applyNluScheduleResult(nluResult, userId);
      return scheduleResult.reply;
    } catch {
      // Fall back below if native model call encounters issue
    }
  }

  return processCommand(userText, userId);
};
